// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiddlewarePractice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205095622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayementType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasDiscriminator<string>("PayementType").HasValue("Payment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CardPayment", b =>
                {
                    b.HasBaseType("Payment");

                    b.Property<string>("CardHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardNumber")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Card");
                });

            modelBuilder.Entity("UPIPayment", b =>
                {
                    b.HasBaseType("Payment");

                    b.Property<string>("UpiId")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("UPIPayement");
                });

            modelBuilder.Entity("WalletPayment", b =>
                {
                    b.HasBaseType("Payment");

                    b.Property<string>("WalletProvider")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("WalletPayment");
                });
#pragma warning restore 612, 618
        }
    }
}
